### ISSUE TITLE
webauthn not added to window?

### ISSUE THREAD

**Issue by apowers313** [adrianba/fido-snippets#1]
webauthn is left as a [global variable](https://github.com/adrianba/fido-snippets/blob/master/polyfill/webauthn.js#L3) rather than adding it to window.webauthn, so the final step of making this a true polyfill is left as an exercise for the user...

**Comment by adrianba** [comment]
The global scope is the window so a global variable is automatically on window.

Try

```
var xyz = "123";
alert(window.xyz);
```

**Comment by apowers313** [comment]
Thanks -- you're right. Not sure why my `assert` was failing before, but it works now.
