### ISSUE TITLE
documentation for InvalidAccessError?

### ISSUE THREAD

**Issue by apowers313** [adrianba/fido-snippets#2]
When running the following code:

``` js

var Helpers = {
    account: {
        default: {
            rpDisplayName: "ACME Corporation",
            displayName: "John P. Smith",
            name: "john.p.smith@example.com",
            id: "5757dfa7-c89d-4ff5-a820-b8a6cbdea281",
            imageURL: "http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"
        },
    },
    cryptoParameters: {
        default: {
            type: 'ScopedCred',
            algorithm: 'RSASSA-PKCS1-v1_5'
        }
    },
    attestationChallenge: {
        default: "a76262397000461a8feae698b1a9712714e9aa740ddf4073901a30b9e2aa5a59"
    }
};


    window.webauthn.makeCredential(Helpers.account.default, Helpers.cryptoParameters.default, Helpers.attestationChallenge.default, undefined, undefined, undefined)
      .then(function(result) {
        console.log("Promise resolved successfully:", result);
        done();
      })
      .catch(function(err) {
        // assert.fail("no error", err, "Promise should not have failed");
        console.log("promiseResolveSuccess Error:", err);
        done(err);
      });
```

I get the result: "promiseResolveSuccess Error: InvalidAccessError". It's not entirely clear to me whether this is because Hello is misconfigured / unavailable; some sort of db error; or something else entirely.

Any hints as to how to resolve this error?

**Comment by adrianba** [comment]
The cryptoParameters.default should be an array:

```
    cryptoParameters: {
        default: [{
            type: 'ScopedCred',
            algorithm: 'RSASSA-PKCS1-v1_5'
        }]
    },
```

**Comment by apowers313** [comment]
It's actually passing in `Helpers.cryptoParameters.default` which is an array.

(Not that you care, but the reason for that is that there will soon be other `cryptoParameters` other than `.default` such as `.badType` or `.badAlgorithm`)

**Comment by adrianba** [comment]
Your code snippet above doesn't pass an array. When I copy your code and make the modification in my comment above to change it into an array then the code runs and I see the makeCredential prompt.

**Comment by apowers313** [comment]
Sorry, I see what you're saying now... I thought it was already an array. Let me verify and get back to you.

**Comment by apowers313** [comment]
That did the trick, thanks again and sorry for the silly question.

For anyone playing along from home, [msCredential docs can be found here](https://msdn.microsoft.com/en-us/library/mt697638%28v=vs.85%29.aspx) (although error conditions are still underspecified, just as they are in the W3C spec -- w3c/webauthn#53 :).
